In [121]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.metrics import f1_score, mean_squared_error, accuracy_score,r2_score
from sklearn.datasets import load_wine
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor

In [122]:
data = load_wine()
X = data.data
y = data.target

df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = data.target

df.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0

In [123]:
df['target'].value_counts()

target
1    71
0    59
2    48
Name: count, dtype: int64

In [124]:
X = df.drop('target',axis=1)
y = df['target']

In [125]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [126]:
dt_clr = DecisionTreeClassifier()

In [127]:
dt_clr.fit(X_train,y_train)

DecisionTreeClassifier()

In [128]:
y_pred = dt_clr.predict(X_test)

In [129]:
f1 = f1_score(y_test,y_pred,average='weighted')
f1

0.9439974457215836

In [130]:
rf_clr = RandomForestClassifier()

In [131]:
rf_clr.fit(X_train,y_train)

RandomForestClassifier()

In [132]:
y_pred = rf_clr.predict(X_test)

In [133]:
f1 = f1_score(y_test,y_pred,average='weighted')
f1

1.0

In [134]:
param_grid_rf = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10]
}

In [135]:
grid_search_rf = GridSearchCV(estimator=RandomForestClassifier(),
                              param_grid=param_grid_rf,
                              scoring='f1_weighted',
                              cv=5)
grid_search_rf.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'max_depth': [None, 10, 20, 30],
                         'min_samples_split': [2, 5, 10],
                         'n_estimators': [50, 100, 200]},
             scoring='f1_weighted')

In [136]:
print("Best Parameters for Random Forest Classifier:", grid_search_rf.best_params_)
print("Best F1 Score from GridSearchCV:", grid_search_rf.best_score_)

Best Parameters for Random Forest Classifier: {'max_depth': None, 'min_samples_split': 2, 'n_estimators': 200}
Best F1 Score from GridSearchCV: 0.9782952128219708

In [137]:
X = df.drop(['target', 'alcohol'],axis=1)
y= df['alcohol']

In [138]:
dl_r = DecisionTreeRegressor()

In [139]:
dl_r.fit(X_train,y_train)

DecisionTreeRegressor()

In [140]:
y_pred = dl_r.predict(X_test)

In [141]:
mse = mean_squared_error(y_test,y_pred)
mse

0.16666666666666666

In [142]:
r2 = r2_score(y_test,y_pred)
r2

0.7142857142857142

In [143]:
rf_r = RandomForestRegressor()

In [144]:
rf_r.fit(X_train,y_train)

RandomForestRegressor()

In [145]:
y_pred= rf_r.predict(X_test)

In [146]:
mse = mean_squared_error(y_test,y_pred)
mse

0.06803888888888888

In [147]:
r2_score = r2_score(y_test,y_pred)
r2_score

0.8833619047619048

In [148]:
param_dist_rf_r = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10]
}

In [149]:
random_search_rf_r = RandomizedSearchCV(estimator=RandomForestRegressor(),
                                          param_distributions=param_dist_rf_r,
                                          scoring='neg_mean_squared_error',
                                          cv=5,
                                          n_iter=10,
                                          random_state=42)
random_search_rf_r.fit(X_train, y_train)

RandomizedSearchCV(cv=5, estimator=RandomForestRegressor(),
                   param_distributions={'max_depth': [None, 10, 20, 30],
                                        'min_samples_split': [2, 5, 10],
                                        'n_estimators': [50, 100, 200]},
                   random_state=42, scoring='neg_mean_squared_error')

In [150]:
print("Best Parameters for Random Forest Regressor:", random_search_rf_r.best_params_)
print("Best Negative MSE from RandomizedSearchCV:", random_search_rf_r.best_score_)

Best Parameters for Random Forest Regressor: {'n_estimators': 100, 'min_samples_split': 5, 'max_depth': 10}
Best Negative MSE from RandomizedSearchCV: -0.04418165529780057